### ISSUE TITLE
configuring cloudflare logpush to loki

### ISSUE THREAD

**Issue by BIJODEV** [pew/cloudflare-worker-logpush-loki#6]
Hi Pew,

Thank you for your contributions for this cloudflare loki.

We were trying to use the cloudflare logpush to directly hit the loki "destination_conf" which unfortunately is not working

Below the curl command which we are using
`curl --location 'https://api.cloudflare.com/client/v4/zones/<zone_id>/logpush/jobs' \
--header 'Content-Type: application/json' \
--header 'X-Auth-Email: <Email>’ \
--header 'X-Auth-Key: <Auth Key>’ \
--header 'Cookie: <cookie value>’ \
--data '{
    "name": "http",
    "logpull_options": "fields=CacheCacheStatus,CacheReserveUsed,CacheResponseBytes,CacheResponseStatus,CacheTieredFill,ClientASN,ClientCountry,ClientDeviceType,ClientIP,ClientIPClass,ClientMTLSAuthCertFingerprint,ClientMTLSAuthStatus,ClientRegionCode,ClientRequestBytes,ClientRequestHost,ClientRequestMethod,ClientRequestPath,ClientRequestProtocol,ClientRequestReferer,ClientRequestScheme,ClientRequestSource,ClientRequestURI,ClientRequestUserAgent,ClientSSLCipher,ClientSSLProtocol,ClientSrcPort,ClientTCPRTTMs,ClientXRequestedWith,ContentScanObjResults,ContentScanObjTypes,Cookies,EdgeCFConnectingO2O,EdgeColoCode,EdgeColoID,EdgeEndTimestamp,EdgePathingOp,EdgePathingSrc,EdgePathingStatus,EdgeRequestHost,EdgeResponseBodyBytes,EdgeResponseBytes,EdgeResponseCompressionRatio,EdgeResponseContentType,EdgeResponseStatus,EdgeServerIP,EdgeStartTimestamp,EdgeTimeToFirstByteMs,LeakedCredentialCheckResult,OriginDNSResponseTimeMs,OriginIP,OriginRequestHeaderSendDurationMs,OriginResponseBytes,OriginResponseDurationMs,OriginResponseHTTPExpires,OriginResponseHTTPLastModified,OriginResponseHeaderReceiveDurationMs,OriginResponseStatus,OriginResponseTime,OriginSSLProtocol,OriginTCPHandshakeDurationMs,OriginTLSHandshakeDurationMs,ParentRayID,RayID,RequestHeaders,ResponseHeaders,SecurityAction,SecurityActions,SecurityRuleDescription,SecurityRuleID,SecurityRuleIDs,SecuritySources,SmartRouteColoID,UpperTierColoID,WAFAttackScore,WAFFlags,WAFMatchedVar,WAFRCEAttackScore,WAFSQLiAttackScore,WAFXSSAttackScore,WorkerCPUTime,WorkerStatus,WorkerSubrequest,WorkerSubrequestCount,WorkerWallTimeUs,ZoneName&timestamps=unixnano",
    "destination_conf": "https://loki.test.io/loki/api/v1/push?header_Authorization=Basic%20<basic Auth>&job=cloudflare-dev-http&tenant_id=1”, 
    "max_upload_bytes": 5000000,
    "max_upload_records": 1000,
    "dataset": "http_requests",
    "frequency": "high",
    "enabled": true
}'`

error output:
`{"success":false,"errors":[{"code":10000,"message":"Authentication error"}]}`

The other way of installing wrangler, I am not aware and also not sure how to do it, is it using terraform ? We are using cloudflare workers for some other means but not familiar on how to do this for logpush. Can you please guide or advice us what is the right way to do it.

**Comment by pew** [comment]
> error output:
> 
> `{"success":false,"errors":[{"code":10000,"message":"Authentication error"}]}`
> 


the error message indicates that you didn't successfully authenticate against the Cloudflare API. Did you use your email address and global API key? If you used the scoped API keys, make sure to have the right permissions, I think there's a scope with _Log_ and you need read/write permissions.
